export const FETCH_LIST = {
    START: 'FETCH_LIST_START',
    SUCCESS: 'FETCH_LIST_SUCCESS',
    ERROR: 'FETCH_LIST_ERROR'
};

export const GET_LOCATION = {
    START: 'GET_LOCATION_START',
    SUCCESS: 'GET_LOCATION_SUCCESS',
    ERROR: 'GET_LOCATION_ERROR'
};
